[package]
name = "robodrive_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
simulation= {path = "./simulation"}

[workspace]
members = [
    "core",
    "sensor",
    "navigation",
    "control",
    "perception",
    "simulation"
]
